server:
  port: 8002

management:
  endpoints:
    ##web管理
    web:
      ##暴露端点
      exposure:
        ##包括
        include:
          - info
          - health
          ##配置刷新端点
          - refresh