server:
  port: 8002
management:
  endpoints:
    ##web管理
    web:
      ##暴露端点
      exposure:
        ##包括
        include:
          - info
          - health
          ##配置刷新端点
          - refresh
spring:
  ##用于集成bus
  rabbitmq:
    host: 192.168.1.6
    port: 5672
    username: guest
    password: guest  ##zipkin
  zipkin:
    ##调用链路数据传输地址
    base-url: http://localhost:9411
    ##调用链路
    sleuth:
      ##取样器
      sampler:
        ##每次都进行采取
        probability: 1