server:
  port: 2001
spring:
  application:
    name: seata-order-service
  cloud:
    alibaba:
      ##配置seata服务
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
    ##配置nacos：seata服务也会被注册到nacos
    nacos:
      discovery:
        server-addr: localhost:8848
  ##配置数据源
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.6:3307/seata_order
    username: root
    password: root
##配置mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml