server:
 port: 7002
spring:
 profiles:
  active: cluster
#  active: single
#eureka-server端配置
eureka:
 instance:
  hostname: eureka7002.com  #eureka服务端的实例名字
 client:
  register-with-eureka: false    #表示不向注册中心注册自己
  fetch-registry: false  #表示并不需要去检索服务（自己就是注册中心，职责是维护服务实例）
  service-url:
   #设置与eureka-server交互的地址：查询服务和注册服务都需要依赖这个地址
   defaultZone: ${eureka.client.service-url.defaultZone}
 server:
  #关闭自我保护机制
  enable-self-preservation: false
  #设置心跳检测的触发时间:2s
  eviction-interval-timer-in-ms: 2000
