server:
  port: 9001
#设置服务名
spring:
  application:
    name: feign-client
  ##zipkin
  zipkin:
    ##调用链路数据传输地址
    base-url: http://localhost:9411
    enabled: true #启用zipkin：默认为true
  ##调用链路
  sleuth:
    ##取样器
    sampler:
      ##每次都进行采取
      probability: 1
#eureka客户端
eureka:
 client:
  register-with-eureka: true
  fetchRegistry: true
  service-url:
    #defaultZone: http://localhost:7001/eureka
    #集群配置
    defaultZone:  http://eureka7002.com:7002/eureka,http://eureka7001.com:7001/eureka

##控制ribbon调用时间
ribbon:
 ##响应时间
 ReadTimeout: 2000
 ##连接时间
 ConnectTimeout: 2000

feign:
  client:
    config:
        default: #默认配置 适用于所有服务
            connectTimeout: 2000 #连接超时时间  2秒
            readTimeout: 2000 #读取超时时间 2秒
            retryer: start.feign.config.CustomRetryer #重试机制
        specific-service-name:  # 针对某个特定服务的配置
          connectTimeout: 3000
          readTimeout: 7000
